# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.ssh.username = "rramos"
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.define "puppetmaster" do |puppetmaster|
    puppetmaster.vm.box = "nhadie/base-precise-64"
    puppetmaster.vm.box_version = "1.0.1"
    puppetmaster.vm.hostname = "puppetmaster.nhadiemonio.com"
    puppetmaster.vm.provision "shell", path: "provision_puppetmaster.sh"
    puppetmaster.vm.network "private_network", ip: "172.28.128.8"
  end

  config.vm.define "client" do |client|
    client.vm.box = "nhadie/base-precise-64"
    client.vm.box_version = "1.0.1"
    client.vm.hostname = "client.nhadiemonio.com"
    client.vm.provision "shell", path: "provision.sh"
    client.vm.network "private_network", ip: "172.28.128.16"
  end

  config.vm.define "ldap" do |ldap|
    ldap.vm.box = "nhadie/base-precise-64"
    ldap.vm.box_version = "1.0.1"
    ldap.vm.hostname = "ldap.nhadiemonio.com"
    ldap.vm.provision "shell", path: "provision.sh"
    ldap.vm.network "private_network", ip: "172.28.128.32"
  end

  config.vm.define "web" do |web|
    web.vm.box = "nhadie/base-precise-64"
    web.vm.box_version = "1.0.1"
    web.vm.hostname = "web.nhadiemonio.com"
    web.vm.provision "shell", path: "provision.sh"
    web.vm.network "private_network", ip: "172.28.128.64"
  end

  config.vm.define "db" do |db|
    db.vm.box = "nhadie/base-precise-64"
    db.vm.box_version = "1.0.1"
    db.vm.hostname = "db.nhadiemonio.com"
    db.vm.network "private_network", ip: "172.28.128.96"
  end

end
